import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

export const Cabecalho = () => {
    var logo=require('../components/img/logo.png');
    return(
    <div lang="pt-br">
        <Head>
            <title>Create Next App</title>
            <meta charSet="utf-8"></meta>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <header className="section-header"> 
            <section className="header-main" style={{background: '#802c6e'}}>
                <div className="container">
                    <div className="row gy-3 align-items-center">
                        <div className="col-lg-2 col-sm-4 col-4">
                            <a href="/" className="navbar-brand">
                            <Image src={logo} width={56} height={54} alt="Logo fake store api" priority/>
                            </a>
                        </div>
                        <div className="order-lg-last col-lg-5 col-sm-8 col-8">
                            <div className="float-end">
                                <a href="#!" className="bnt-navbar"> 
                                    <i className="fa fa-user"></i>  <span className="ms-1 d-none d-sm-inline-block">Sign in  </span> 
                                </a>
                                <a href="#!" className="bnt-navbar"> 
                                    <i className="fa fa-heart"></i>  <span className="ms-1 d-none d-sm-inline-block">Wishlist</span>   
                                </a>
                                <Link data-bs-toggle="offcanvas" href="/cart" className="bnt-navbar"> 
                                    <i className="fa fa-shopping-cart"></i> <span className="ms-1">My cart </span> 
                                </Link>
                            </div>
                        </div>
                        <div className="col-lg-5 col-md-12 col-12">
                            <form action="#!">
                            <div className="input-group">
                                <input type="search" className="form-control" style={{width: '55%'}} placeholder="Search"/>
                                <select className="form-select">
                                <option value="">All type</option>
                                <option value="codex">Special</option>
                                <option value="comments">Only best</option>
                                <option value="content">Latest</option>
                                </select>
                                <button className="btn btn-dark">
                                <i className="fa fa-search"></i> 
                                </button>
                            </div>
                            </form>
                        </div>   
                    </div>
                </div>
            </section>

            <nav className="navbar navbar-dark bg-dark navbar-expand-lg">
                <div className="container">
                    <button className="navbar-toggler border" type="button" data-bs-toggle="collapse" data-bs-target="#navbar_main">
                        <span className="navbar-toggler-icon"></span>
                    </button>
                    
                    <div className="collapse navbar-collapse" id="navbar_main">
                        <ul className="navbar-nav">
                            <li className="nav-item">
                                <a className="nav-link ps-0 text-white" href="#!"> Categories </a>
                            </li>
                            <li className="nav-item">
                                <a className="nav-link text-white" href="#!">Hot offers</a>
                            </li>
                            <li className="nav-item">
                                <a className="nav-link text-white" href="#!">Gift boxes</a>
                            </li>
                            <li className="nav-item">
                                <a className="nav-link text-white" href="#!">Projects</a>
                            </li>
                            <li className="nav-item">
                                <a className="nav-link text-white" href="#!">Menu item</a>
                            </li>
                            <li className="nav-item">
                                <a className="nav-link text-white" href="#!">Menu name</a>
                            </li>
                            <li className="nav-item dropdown">
                                <a className="dropdown-toggle nav-link text-white" href="#!" data-bs-toggle="dropdown" aria-expanded="false">
                                    Others
                                </a>
                                <ul className="dropdown-menu">
                                    <li> <a className="dropdown-item" href="#!">Submenu one </a> </li>
                                    <li> <a className="dropdown-item" href="#!">Submenu two</a> </li>
                                    <li> <a className="dropdown-item" href="#!">Submenu three</a> </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" />
    </div>
    )
}