import Head from 'next/head'

export const CardProductsTop = () => {
    return(
    <div lang="pt-br">
        <Head>
            <title>Create Next App</title>
            <meta charSet="utf-8"></meta>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <section className="section-intro padding-top-sm" style={{paddingTop: '60px'}}>
            <div className="container">
                <main className="card p-3">
                    <div className="row">
                        <aside className="col-lg-3"> 
                            <nav className="nav flex-column nav-pills">
                                <a className="nav-link active" aria-current="page" href="#!" style={{background: '#802c6e'}}>Electronics</a>
                                <a className="nav-link" href="#!">Clothes and wear</a>
                                <a className="nav-link" href="#!">Jewelery</a>
                                <a className="nav-link" href="#!">Computer and tech</a>
                                <a className="nav-link" href="#!">Tools, equipments</a>
                                <a className="nav-link" href="#!">Sports and outdoor</a>
                                <a className="nav-link" href="#!">Animal and pets</a>
                                <a className="nav-link" href="#!">Machinery tools</a>
                                <a className="nav-link" href="#!">Other products</a>
                            </nav>
                        </aside>
                        <div className="col-lg-9">
                            <article className="card-banner p-5" style={{height: '360px', backgroundImage: `url('https://bootstrap-ecommerce.com/bootstrap5-ecommerce/images/banners/banner1.webp')`}}>
                                <div className="card-teste" style={{maxWidth: '500px'}}>
                                    <h2 className="text-white">Great products with <br/> best deals </h2>
                                    <p className="text-white">No matter how far along you are in your sophistication as an amateur astronomer, there is always one.</p>
                                    <a href="#!" className="btn" style={{background: '#802c6e', color: '#FFF', border: 'none'}}> View more </a>
                                </div>
                            </article>
                        </div>
                    </div>
                </main>
            </div>
        </section>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" />
    </div>
    )
}