import Head from "next/head";

export const CardImageCenter = () => {
    return(
    <div lang="pt-br">
        <Head>
            <title>Create Next App</title>
            <meta charSet="utf-8"></meta>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <section className="padding-top">
          <div className="container-teste">
            <div className="row gy-4">
              <aside className="col-lg-6">
                <article className="card-banner-center bg-gray h-100" style={{minHeight: '200px'}}>
                  <div className="p-3 p-lg-5" style={{maxWidth: '70%'}}>
                    <h3> Best products &amp; brands in our store at 80% off</h3>
                    <p>That's true but not always</p>
                    <a className="btn text-white" href="#" style={{backgroundColor: '#802c6e'}}> Claim offer </a>
                  </div>
                    <img src="https://bootstrap-ecommerce.com/bootstrap5-ecommerce/images/banners/banner-item2.webp" height={350} className="img-bg"/>
                </article>
              </aside>
              <aside className="col-lg-6">
                <div className="row mb-4">
                  <div className="col-6">
                    <article className="card card-center" style={{minHeight: '200px', background: '#FFF', backgroundImage: `url('https://bootstrap-ecommerce.com/bootstrap5-ecommerce/images/banners/banner3.webp')`}}>
                      <div className="card-body">
                        <h5 className="text-white">Gaming toolset</h5>
                        <p className="text-white">Technology for cyber sport  </p>
                        <a className="btn btn-dark btn-sm" href="#!">Learn more</a>
                      </div>
                    </article>
                  </div>
                  <div className="col-6">
                    <article className="card card-center" style={{minHeight: '200px', background: '#FFF', backgroundImage: `url('https://bootstrap-ecommerce.com/bootstrap5-ecommerce/images/banners/banner2.webp')`}}>
                      <div className="card-body">
                        <h5 className="text-white">Quality sound</h5>
                        <p className="text-white">All you need for music</p>
                        <a className="btn btn-dark btn-sm" href="#!">Learn more</a> 
                      </div>
                    </article>
                  </div>
                </div>

                <article className="card card-center" style={{minHeight: '200px', backgroundImage: `url('https://bootstrap-ecommerce.com/bootstrap5-ecommerce/images/banners/banner1.webp')`}}>
                  <div className="card-body card-teste">
                    <h5 className="text-white">Buy 2 items, With special gift</h5>
                    <p className="text-white" style={{maxWidth: '400px'}}>Buy one, get one free marketing strategy helps your business improves the brand by sharing the profits </p>
                    <a className="btn btn-dark btn-sm" href="#!">Learn more</a> 
                  </div>
                </article>
              </aside>
            </div>
          </div>
        </section>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" />
    </div>
    )
}