import Image from 'next/image'
import Head from 'next/head'

export const Footer = () => {
   var logo=require('../components/img/logo.png');
      return(
      <div lang="pt-br">
         <Head>
            <title>Create Next App</title>
            <meta charSet="utf-8"></meta>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <footer>
            <div className="footer-wrap">
               <div className="container first_class">
                  <div className="row">
                     <div className="col-md-4 col-sm-6">
                        <h3>Fake Store API</h3>
                        <p>Fake store rest API for your e-commerce or shopping website prototype. Contact by email for more information.</p>
                     </div>
                     <div className="col-md-4 col-sm-6">
                        <form className="newsletter d-flex">
                           <input className="form-control" type="text" placeholder="E-mail"/>
                           <a className="newsletter_submit_btn" href="#!" target="_blank" rel="noreferrer"><i className="fa fa-paper-plane"></i></a>
                        </form>
                     </div>
                     <div className="col-md-4 col-sm-6">
                        <div className="col-md-12">
                           <div className="standard_social_links">
                              <div>
                                 <li className="round-btn btn-facebook"><a href="#!" target="_blank" rel="noreferrer"><i className="fab fa-facebook-f"></i> </a></li>
                                 <li className="round-btn btn-linkedin"><a href="#!" target="_blank" rel="noreferrer"><i className="fab fa-linkedin-in" aria-hidden="true"></i> </a></li>
                                 <li className="round-btn btn-twitter"><a href="#!" target="_blank" rel="noreferrer"><i className="fab fa-twitter" aria-hidden="true"></i> </a></li>
                                 <li className="round-btn btn-instagram"><a href="#!" target="_blank" rel="noreferrer"><i className="fab fa-instagram" aria-hidden="true"></i> </a></li>
                                 <li className="round-btn btn-whatsapp"><a href="#!" target="_blank" rel="noreferrer"><i className="fab fa-whatsapp" aria-hidden="true"></i> </a></li>
                                 <li className="round-btn btn-envelop"><a href="#!" target="_blank" rel="noreferrer"><i className="fa fa-envelope" aria-hidden="true"></i> </a></li>
                              </div>
                           </div>   
                        </div>
                     </div>
                  </div>
               </div>

               <div className="second_class">
                  <div className="container second_class_bdr">
                     <div className="row">
                        <div>
                           <div className="footer-logo d-flex justify-content-center"><Image src={logo} width={80} height={70} alt="Logo fake store api" priority/>
                           </div>
                           <h5 className="d-flex justify-content-center">Get tired of Lorem ipsum data?!</h5>
                           <h5 className="d-flex justify-content-center">Didn't you find any free e-commerce API?!</h5>
                           <p className="container d-flex justify-content-center" style={{textAlign: 'center'}}>fakeStoreApi is a free online REST API that you can use whenever you need Pseudo-real data for your e-commerce or shopping website without running any server-side code. It's awesome for teaching purposes, sample codes, tests, etc.</p>
                     </div>
                  </div>
               </div>
               </div>
               
               <div className="row">
                  <div className="container-fluid">
                  <div className="copyright"><span style={{marginRight: '10px'}}> © 2022 Copyright </span> | <span style={{marginLeft: '10px'}}><i className="fas fa-mug-hot" style={{marginRight: '5px'}}></i> Buy me a coffee</span></div>
                  </div>
               </div>
            </div>
         </footer>
         <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" />
      </div>
      )
}