import Head from 'next/head'

export const Informations = () => {
    return(
    <div lang="pt-br">
        <Head>
            <title>Create Next App</title>
            <meta charSet="utf-8"></meta>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <section className="padding-informations">
            <div className="container-teste">
                <article className="card-informations p-lg-2">
                    <div className="row g-3" style={{marginLeft: '20px', marginTop: '5px'}}>
                        <div className="col-lg-3 col-md-6"> 
                            <figure className="icontext">
                                <div className="icon">
                                    <span className="icon-sm bg-warning-light rounded">
                                        <i className="fa fa-thumbs-up"></i>
                                    </span>
                                </div>
                                <figcaption className="text">
                                    <h6 className="title">Reasonable prices</h6>
                                    <p>Have you ever finally just  </p>
                                </figcaption>
                            </figure>
                        </div>
                        <div className="col-lg-3 col-md-6"> 
                            <figure className="icontext">
                                <div className="icon">
                                    <span className="icon-sm bg-warning-light rounded">
                                        <i className="fa fa-plane"></i>
                                    </span>
                                </div>
                                <figcaption className="text">
                                    <h6 className="title">Worldwide shipping</h6>
                                    <p>Have you ever finally just  </p>
                                </figcaption>
                            </figure>
                        </div>
                        <div className="col-lg-3 col-md-6"> 
                            <figure className="icontext">
                                <div className="icon">
                                    <span className="icon-sm bg-warning-light rounded">
                                        <i className="fa fa-star"></i>
                                    </span>
                                </div>
                                <figcaption className="text">
                                    <h6 className="title">Best ratings</h6>
                                    <p>Have you ever finally just  </p>
                                </figcaption>
                            </figure>
                        </div> 
                        <div className="col-lg-3 col-md-6"> 
                            <figure className="icontext">
                                <div className="icon">
                                    <span className="icon-sm bg-warning-light rounded">
                                        <i className="fa fa-phone"></i>
                                    </span>
                                </div>
                                <figcaption className="text">
                                    <h6 className="title">Help center</h6>
                                    <p>Have you ever finally just  </p>
                                </figcaption>
                            </figure> 
                        </div> 
                    </div>
                </article>
            </div>
        </section>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" />
    </div>
    )
}