import Image from 'next/image'
import Link from 'next/link'
import Head from 'next/head'

export const Lista = ({teste}) => {
    return(
    <div lang="pt-br">
      <Head>
        <title>Create Next App</title>
        <meta charSet="utf-8"></meta>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="padding-y" style={{paddingTop: '20px'}}>
        <div className="container-teste">
          <div className="row">
            <aside className="col-lg-3">
              <button className="btn btn-outline-secondary mb-3 w-100  d-lg-none" data-bs-toggle="collapse" data-bs-target="#aside_filter">Show filter</button>
              <div id="aside_filter" className="collapse card card-filters d-lg-block mb-5" style={{border: '1px solid rgba(81,88,94,.12)'}}>
                <article className="filter-group">
                  <header className="card-header" style={{borderBottom: '1px solid #ccc'}}>
                    <a href="#!" className="title" data-bs-toggle="collapse" data-bs-target="#collapse_aside1">
                      <i className="icon-control fa fa-chevron-down"></i>   Related items 
                    </a>
                  </header>
                  <div className="collapse show" id="collapse_aside1">
                    <div className="card-body" style={{marginLeft: '-25px'}}>
                      <ul className="list-menu" style={{listStyle: 'none'}}>
                        <li><a href="#!">Electronics </a></li>
                        <li><a href="#!">Accessories  </a></li>
                        <li><a href="#!">Home items </a></li>
                        <li><a href="#!">Men's clothing </a></li>
                        <li><a href="#!">Interior items </a></li>
                        <li><a href="#!">Magazines </a></li>
                        <li><a href="#!">Category name </a></li>
                        <li><a href="#!">Home items </a></li>
                      </ul>
                    </div>
                  </div>
                </article>
                <article className="filter-group">
                  <header className="card-header" style={{borderBottom: '1px solid #ccc'}}>
                    <a href="#!" className="title" data-bs-toggle="collapse" data-bs-target="#collapse_aside_brands">
                      <i className="icon-control fa fa-chevron-down"></i>  Brands 
                    </a>
                  </header>
                  <div className="collapse show" id="collapse_aside_brands">
                    <div className="card-body">
                      <label className="form-check mb-2">
                        <input className="form-check-input" type="checkbox" value="" defaultChecked={true}/>
                        <span className="form-check-label"> Eletronics </span>
                        <b className="badge rounded-pill bg-gray-dark float-end">10</b>
                      </label>

                      <label className="form-check mb-2">
                        <input className="form-check-input" type="checkbox" value="" defaultChecked={true}/>
                        <span className="form-check-label"> Jewelery </span>
                        <b className="badge rounded-pill bg-gray-dark float-end">8</b>
                      </label>

                      <label className="form-check mb-2">
                        <input className="form-check-input" type="checkbox" value="" defaultChecked={true}/>
                        <span className="form-check-label"> Men's clothing </span>
                        <b className="badge rounded-pill bg-gray-dark float-end">15</b>
                      </label>

                      <label className="form-check mb-2">
                        <input className="form-check-input" type="checkbox" value="" defaultChecked={true}/>
                        <span className="form-check-label"> Women's clothing </span>
                        <b className="badge rounded-pill bg-gray-dark float-end">29</b>
                      </label>

                      <label className="form-check mb-2">
                        <input className="form-check-input" type="checkbox" value=""/>
                        <span className="form-check-label"> Animal and pets </span>
                        <b className="badge rounded-pill bg-gray-dark float-end">30</b>
                      </label>

                      <label className="form-check mb-2">
                        <input className="form-check-input" type="checkbox" value=""/>
                        <span className="form-check-label"> Other products </span>
                        <b className="badge rounded-pill bg-gray-dark float-end">30</b>
                      </label>
                    </div>
                  </div>
                </article>
                <article className="filter-group">
                  <header className="card-header" style={{borderBottom: '1px solid #ccc'}}>
                    <a href="#!" className="title" data-bs-toggle="collapse" data-bs-target="#collapse_aside2">
                      <i className="icon-control fa fa-chevron-down"></i>  Price 
                    </a>
                  </header>
                  <div className="collapse show" id="collapse_aside2">
                    <div className="card-body">
                      <input type="range" className="form-range" min="0" max="100"/>
                      <div className="row mb-3">
                        <div className="col-6">
                          <label htmlFor="min" className="form-label">Min</label>
                          <input className="form-control" id="min" placeholder="$0" type="number"/>
                        </div>
                        <div className="col-6">
                          <label htmlFor="max" className="form-label">Max</label>
                          <input className="form-control" id="max" placeholder="$1,0000" type="number"/>
                        </div>
                      </div>
                      <button className="btn btn-dark w-100" type="button">Apply</button>
                    </div>
                  </div>
                </article>
                <article className="filter-group">
                  <header className="card-header" style={{borderBottom: '1px solid #ccc'}}>
                    <a href="#!" className="title" data-bs-toggle="collapse" data-bs-target="#collapse_aside3">
                      <i className="icon-control fa fa-chevron-down"></i>  Size 
                    </a>
                  </header>
                  <div className="collapse show" id="collapse_aside3">
                    <div className="card-body">
                        <label className="checkbox-btn" style={{marginLeft: "10px"}}>
                          <input type="checkbox"/>
                          <span className="btn btn-light"> XS </span>
                        </label>

                        <label className="checkbox-btn" style={{marginLeft: "10px"}}>
                          <input type="checkbox"/>
                          <span className="btn btn-light"> SM </span>
                        </label>

                        <label className="checkbox-btn" style={{marginLeft: "10px"}}>
                          <input type="checkbox"/>
                          <span className="btn btn-light"> LG </span>
                        </label>

                        <label className="checkbox-btn" style={{marginLeft: "10px"}}>
                          <input type="checkbox"/>
                          <span className="btn btn-light"> XXL </span>
                        </label>
                    </div>
                  </div>
                </article>
                <article className="filter-group">
                  <header className="card-header" style={{borderBottom: '1px solid #ccc'}}>
                    <a href="#!" className="title" data-bs-toggle="collapse" data-bs-target="#collapse_aside4">
                      <i className="icon-control fa fa-chevron-down"></i> Condition
                    </a>
                  </header>
                  <div className="collapse show" id="collapse_aside4">
                    <div className="card-body">
                      <div className="form-check mb-3">
                          <input className="form-check-input" type="checkbox" value="new" id="condition-checkbox"/>
                          <label className="form-check-label text-uppercase small text-muted" htmlFor="condition-checkbox">
                              New
                          </label>
                      </div>
                      <div className="form-check mb-3">
                          <input className="form-check-input" type="checkbox" value="new" id="condition-checkbox"/>
                          <label className="form-check-label text-uppercase small text-muted" htmlFor="condition-checkbox">
                              Used
                          </label>
                      </div>
                      <div className="form-check mb-3">
                          <input className="form-check-input" type="checkbox" value="new" id="condition-checkbox"/>
                          <label className="form-check-label text-uppercase small text-muted" htmlFor="condition-checkbox">
                              Collectible
                          </label>
                      </div>
                      <div className="form-check mb-3">
                          <input className="form-check-input" type="checkbox" value="new" id="condition-checkbox"/>
                          <label className="form-check-label text-uppercase small text-muted" htmlFor="condition-checkbox">
                              Renewed
                          </label>
                      </div>
                    </div>
                  </div>
                </article>
              </div>
            </aside>

            <main className="col-lg-9">
              <header className="d-sm-flex align-items-center border-bottom mb-4 pb-3">
                <strong className="d-block py-2">{teste.length} Items found </strong>
                <div className="ms-auto">
                  <select className="form-select d-inline-block w-auto" style={{marginRight: '5px'}}>
                    <option value="0">Best match</option>
                    <option value="1">Recommended</option>
                    <option value="2">High rated</option>
                    <option value="3">Randomly</option>
                  </select>
                  <div className="btn-group">
                    <a href="#!" className="btn btn-light" data-bs-toggle="tooltip" title="" data-bs-original-title="List view"> 
                      <i className="fa fa-bars"></i>
                    </a>
                    <a href="#!" className="btn btn-light active" data-bs-toggle="tooltip" title="" data-bs-original-title="Grid view"> 
                      <i className="fa fa-th"></i>
                    </a>
                  </div>
                </div>
              </header>

              <div className="container mt-2 mb-5">
                <div className="row">
                  <div className="col-md-20" style={{marginTop: '-30px'}}>
                    {teste.map((user) => (
                      <div key={user.id} className="row p-2 bg-white border rounded card-principal" style={{marginTop: '30px'}}>  
                        <div className="col-md-2 mt-1 image-center"><Image className="img-fluid img-responsive rounded" src={user.image} width={125} height={120} alt="Imagens de produtos fake api" priority/></div>
                          <div className="col-md-7 mt-1">
                            <h5 className="font-weight-bold" style={{marginBottom: '15px', paddingTop: '15px'}}>{user.title}</h5>
                              <div className="d-flex flex-row">
                                <div className="ratings mr-2"><div className="stars-outer"><div className="stars-inner"></div></div></div><span style={{marginLeft: '5px'}}>{user.rating.rate}</span>
                              </div>
                              <div className="mt-1 mb-1 spec-1" style={{paddingTop: '5px'}}><span>{user.category}</span></div>
                              <p className="text-justify text-truncate para mb-0" style={{color: '#000'}}>{user.description}<br /><br /></p>
                          </div>
                          <div className="align-items-center align-content-center col-md-3 border-left mt-1">
                            <div className="d-flex flex-row align-items-center">
                              <h4 className="mr-1">${user.price}</h4><span className="strike-text">$249.99</span>
                            </div>
                            <h6 className="text-success">Free shipping <i className="fas fa-plane-departure" style={{marginLeft: '5px'}}></i></h6>
                            <div className="d-flex flex-column mt-4"><Link className="btn btn-primary btn-sm btn-details d-flex align-items-center justify-content-center" type="button" href='/details/[id]'as={`/details/${user.id}`} rel="stylesheet preload">Details</Link>
                            <button className="btn btn-outline-primary btn-sm mt-2" type="button"><Link className='text-decoration-none btn-outline-primary' href='/cart/[id]'as={`/cart/${user.id}`} rel="stylesheet preload"> Add to cart</Link></button></div>
                          </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </main>
          </div>
        </div>
      </section>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" />
    </div>
    )
}